### ISSUE TITLE
Generic "holes" for containers with unlimited number of components in a single row

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#104]
I'd propose to have a `&__hole` element for every container in those sections, which can hold multiple (and dynamic) number of items. Think of it as it is `li` with fixed margin/padding for all holes except `first-child`.

WDYT?

**Comment by mr-mig** [comment]
> Improve quality for styleguide components

**Comment by vergilius** [comment]
@mr-mig WDYT about having `mint-column`, `mint-row` container with items that would care for all children in container instead of `holes`? And maybe also doing some stuff with flexbox, like order?

Few examples:

- **vertical** - element in content-box that would care for margin-bottom under every child except last one:
![image](https://cloud.githubusercontent.com/assets/1142999/9814976/f18525f0-5892-11e5-9629-eb86f94e7655.png)

- **horizontal** - element that cares for margin right for every element
<img width="468" alt="screen shot 2015-09-11 at 14 42 11" src="https://cloud.githubusercontent.com/assets/1142999/9815030/54a0895e-5893-11e5-9050-f1f4a5add68e.png">
<img width="571" alt="screen shot 2015-09-11 at 14 42 01" src="https://cloud.githubusercontent.com/assets/1142999/9815031/54a10212-5893-11e5-8471-162f9230490d.png">

**Comment by mr-mig** [comment]
@vergilius grid can solve those issues. 
But AFAIK we have deliberately set grids aside in the very beginning. I do not know implications though. 

Do you have any idea @kdzwinel @aju @matzimowski?

**Comment by mr-mig** [comment]
`mint-list` can be used for horizontal component with wrapping (row)

**Comment by mr-mig** [comment]
Grid for layout from Zurb: http://zurb.com/article/1333/foundation-a-new-grid

**Comment by mr-mig** [comment]
Apart from that, we have differentiation for **layout** and **container holes**.

We can start this implementation by having `group` and `cell` mixins, so that every container has a special region with element name like `mint-content-box__actions` and `mint-cell`/`mint-hole` inside.

**Comment by mr-mig** [comment]
The group and cell should have these axes:

1. Vertical axis: `top`/`middle`/`bottom` or `start`/`middle`/`end`
2. Horizontal axis: `left`/`center`/`right` or `start`/`center`/end` + `justify`/`spaced`

The latter is ambiguous, but consistent with flexbox properties.

Additionally, group can be `vertical`/`horizontal` (to designate the axis).

**Comment by matzimowski** [comment]
There's some things which need to be addressed for IE10-11, see #462

**Comment by kdzwinel** [comment]
Fix for breadcrumbs:

```
.mint-breadcrumb-list {
    line-height: 1.3rem;
}
```

**Comment by aju** [comment]
We are going into direction of row/column - closing this one
