### ISSUE TITLE
New avatars

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#154]
Avatars have changed. 
See brainly/web-client#111 and brainly/symfony#1511 https://github.com/brainly/symfony/issues/1624
brainly/web-client#103

Summ up:

* [x] Change sizes
* [ ] Change default avatar icon

Edit:
According to Janusz:
Ok. Final decision is: we have three sizes of avatars:
1) 24px with 1px border inside
2) 32px with 1px border inside
3) 48px with 2px border inside

**Comment by mr-mig** [comment]
@matzimowski @JanuszSzewczyk what about the default icon?
We have some issues opened regarding gender-related icons. Should we stick to the current one?

**Comment by JanuszSzewczyk** [comment]
I think we should have separated for man and woman.

**Comment by mr-mig** [comment]
@JanuszSzewczyk any reason?

**Comment by JanuszSzewczyk** [comment]
1. We have this information on registration form. 
2. For some reasons users need help from same gender
3. Now we have this separation
4. This is closer to our users

Maybe it will be a problem for non decided users. If we keep this information the in future we can show them separated gravatars for gender. There were some idea about this.
Do you think different @mr-mig ?

**Comment by mr-mig** [comment]
> For some reasons users need help from same gender

Is it some proven behavior?

I have found this paper, which is a bit different: http://vili.lehdonvirta.com/files/fhbx4348/Lehdonvirta-2012-Avatar-gender-and-help-seeking.pdf

> Now we have this separation

Not a valid argument. 

> This is closer to our users

What does it mean?


You can find set of possible gender-specific avatar problems here: http://ux.stackexchange.com/questions/58102/gender-neutral-photos-for-users-who-dont-yet-have-a-profile-picture

**Comment by mr-mig** [comment]
Otherwise, I do unserstand that there may be a need for gender/age distinction. 
The question is **how does it fit our context**?

**Comment by JanuszSzewczyk** [comment]
I don't want to change something that we have because ... we wan't change it for no reason, and we did not test it, or ask users. Maybe you're right with this "paper" but for me this is not correct time for changing this. If it's good time for this then better is to change asking flow. 
Closer to our users because now they have it and we do not ask them if it's ok or not.
Generally always appear question about sex, nationality, age, level, skin color. This is big question in our social platform how we should work with this problems / challenges.
So ask about this when we finish rebranding. We have a lot of questions. For example how to use our information to connect users together with learning based on not only register informations but what they know, what they want to know, what they are..

**Comment by JanuszSzewczyk** [comment]
Ok, there was misunderstanding. So on design graphics are mistakes. We should stay with sex and avatar for each. We have to paint it. In the future we should think about gender again. Now we should give U 2 avatars.

**Comment by mr-mig** [comment]
Per discussion with @JanuszSzewczyk we come to this conclusion: avatars were supposed to be gender-specific in scope of Rebranding project. We’ve missed that in mockups.
For now we will stick to gender-based avatars, so that it is consistent with the old version. 
The design will be provided.

**Comment by JanuszSzewczyk** [comment]
On Monday you will have it. @JoannaWalusiak will paint it :)

**Comment by JanuszSzewczyk** [comment]
https://www.pixelapse.com/brainly/projects/Rebranding/Materials/Avatar%20HE.svg
https://www.pixelapse.com/brainly/projects/Rebranding/Materials/Avatar%20SHE.svg

**Comment by aju** [comment]
No longer relevant.
